### PR TITLE
feature: add flutter detach command

### PR DESCRIPTION
**Pull request by joshpetit**
#111 

done :)

### CODE REVIEW

**Comment by joshpetit** [comment]
Only thing I'm unsure about is the `command_requests` for the dap runner. not really sure what `detach` would be for it so I just put `detach = "detach"`. Would there be a place for me to verify this?

[The line im talking about](https://github.com/akinsho/flutter-tools.nvim/pull/113/commits/433f242e252ea451ecc2354143ad1498b49844cb#diff-9366d637f63c2f176a54a3e0af43f5e21f3aa6c97e72be09809d49d91711aee0R19)

**Comment by akinsho** [comment]
@joshpetit thanks for working on this, generally looks fine to me. Regarding the `command_requests` @clement-buchart actually added the functionality and tbh I don't know how he figured out which names matched which for the dap runner. Will see if he can enlighten us, otherwise I'll merge this as a best effort we can try and improve on if it doesn't work

**Comment by clement-buchart** [comment]
Hello, 

Looking at https://github.com/Dart-Code/Dart-Code/blob/f58ca38e451d81f4d0e20bbb6b8ebb06a66264a4/src/debug/run_daemon_base.ts#L104 there is a detach method, but it's only ever called if the dap configuration was started in attach mode, and we always start a "launch" configuration. 

So for it to work we would need either : 
- Add some codepath in Dart-Code to be able to call this method explicitly via a request and contribute this upstream.
- Refactor the dap-runner to use an attach configuration. This would imply actually starting the flutter process ourselves and then attaching to it. 
 
First solution is probably simpler to implement and "better", but dependent on another repo.

I personally will not have a lot of time to contribute it is the foreseeable future. 

May I suggest simply not adding anything to the command_requests of the dap runner ? 
This way it should fall back to this codepath which will indicate it's not implemented yet for this runner : 
```  
elseif not quiet then
    utils.notify("Command " .. cmd .. " is not yet implemented for DAP runner")
end
```
(thus current implementation n this PR will do nothing silently)

Cheers.

**Comment by akinsho** [comment]
I agree with omitting the functionality for the dap runner as both alternative options are quite involved. Thanks for the input @clement-buchart 👍🏾

**Comment by joshpetit** [comment]
@akinsho Just removed it 👍

**Comment by akinsho** [comment]
Thanks for the PR @joshpetit just merged it 👍🏿

**Pull request merged**
