### PR TITLE
feat: add install/uninstall cmd to menu

### PR DESCRIPTION
**Pull request by bruce3x**
I added two commands for installing and uninstalling the app, which is useful in the scenario of testing the initial installation of the app.

### CODE REVIEW

**Comment by akinsho** [comment]
@sidlatau any thoughts on this 🙏🏾 LGTM but not gonna be able to try it. Is it useful to have in your opinion

**Comment by bruce3x** [comment]
This feature is inspired by the [adb-idea](https://github.com/pbreault/adb-idea) plugin.
image

**Comment by sidlatau** [comment]
Looks like it does not work when the app uses flavors. For example, to uninstall it should construct such command respecting project configuration:
`flutter install --uninstall-only --flavor dev`
Flavors may be set up in .nvim.lua file in the project:
```lua
require("flutter-tools").setup_project({
	{
		name = "DEV",
		flavor = "dev"
	},
	{
		name = "PROD",
		flavor = "prod"
	},
})

```

**Comment by sidlatau** [comment]
I will close it as it is implemented in /pull/315. Thanks @bruce3x for the initial code!

**Pull request closed without merging**
