### PR TITLE
feat: create overridable notification highlights

### PR DESCRIPTION
**Pull request by akinsho**
This PR allows a user to override highlights to specifically change the colour of flutter tool notifications. Currently, this is only possible by changing global highlight groups

The groups are 
* `FlutterNotificationNormal` - content of the notification
* `FlutterNotificationBorder` - border of the notification

### CODE REVIEW

**Comment by akinsho** [comment]
@ashishbinu can you try using the highlight groups in this PR to see if they work for you.

**Comment by akinsho** [comment]
fixes #63

**Comment by ashishbinu** [comment]
> @ashishbinu can you try using the highlight groups in this PR to see if they work for you.

How can I pull this PR via packer?

**Comment by ashishbinu** [comment]
image
It is working after adding the highlight commands in the setup function in packer.nvim.

image

**Comment by ashishbinu** [comment]
@akinsho Wouldn't it be better to name the `FlutterNotificationNormal` to `FlutterNotficationContent`.

**Comment by akinsho** [comment]
@ashishbinu no not really because the naming follow neovim highlighting convention, if you check the output of `:highlight<CR>` you will see that neovim uses normal for the content of the buffer which is what this is supposed to represent.

Can you clarify if this solves your issue?

**Comment by akinsho** [comment]
Sorry, just noticed your message confirming it was working 👍🏾. Ok I'll update the README and merge this in soon.

**Comment by ashishbinu** [comment]
> @ashishbinu no not really because the naming follows neovim's highlighting convention, if you check the output of `:highlight<CR>` you will see that neovim uses normal for the content of the buffer which is what this is supposed to represent.

If that's the case it seems right to have that name.

>Ok I'll update the README and merge this in soon.

Thanks for this PR.

**Pull request merged**
